version: "3.8"

volumes:
  rabbitmq_data:

services:
  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
      - rabbitmq_data:/var/lib/rabbitmq
 
  ###################################
  # User: The User microservice
  ###################################
  user:
    build:
      context: ./
      dockerfile: user.dockerfile
    image: ngcaijun/user:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      dbURL: mysql+mysqlconnector://root:pSSSS+]q8zZ-pjF@34.124.211.169/user
    ports:
      - "5101:5101"

  #######################################################
  # Shop: The Shop microservice
  #######################################################
  shop:
    build:
      context: ./
      dockerfile: shop.dockerfile
    image: ngcaijun/shop:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      dbURL: mysql+mysqlconnector://root:pSSSS+]q8zZ-pjF:@34.142.233.183/shop
    ports:
      - "5000:5000"

  #######################################################
  # Recommend: The Recommend microservice
  #######################################################
  recommend:
    build:
      context: ./
      dockerfile: recommend.dockerfile
    image: ngcaijun/recommend:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5300:5300"
  
  #######################################################
  # Payment: The Payment microservice
  #######################################################
  payment:
    build:
      context: ./
      dockerfile: payment.dockerfile
    image: ngcaijun/payment:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5666:5666"
  
  #######################################################
  # Error: The Error microservice
  #######################################################
  error:
    build:
      context: ./
      dockerfile: error.dockerfile
    image: ngcaijun/error:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      e_queue_name: Error
      
      PYTHONUNBUFFERED: 1
  
  #######################################################
  # Notification: The Notification microservice
  #######################################################
  notification:
    build:
      context: ./
      dockerfile: notification.dockerfile
    image: ngcaijun/notification:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      a_queue_name: Notification_Log
      payment_failure_queue_name: Notification_Log_Fail
      refund_queue_name: Notification_Refund
    
      PYTHONUNBUFFERED: 1

  ###############################################
  # Create Recommendation: The Create Recommendation microservice
  ###############################################
  create_recommendation:
    build:
      context: ./
      dockerfile: create_recommendation.dockerfile
    image: ngcaijun/create_recommendation:esd
    restart: always
    depends_on:
      - rabbitmq
      - shop
      - user
      - error
      - recommend

    ports:
      - "5500:5500"

    environment:
      PYTHONUNBUFFERED: 1

  ###############################################
  # Make Purchase: The Make Purchase microservice
  ###############################################
  make_purchase:
    build:
      context: ./
      dockerfile: make_purchase.dockerfile
    image: ngcaijun/make_purchase:esd
    restart: always
    depends_on:
      - rabbitmq
      - shop
      - user
      - payment
      - error
      - notification

    ports:
      - "5100:5100"

    environment:
      PYTHONUNBUFFERED: 1

  ###############################################
  # Refund Game: The Refund Game microservice
  ###############################################
  refund_game:
    build:
      context: ./
      dockerfile: refund_game.dockerfile
    image: ngcaijun/refund_game:esd
    restart: always
    depends_on:
      - rabbitmq
      - shop
      - user
      - payment
      - error
      - notification

    ports:
      - "5200:5200"

    environment:
      PYTHONUNBUFFERED: 1
  